baseURL = 'https://www.dawidmacek.com/'
languageCode = 'en-us'
title = "Dawid Macek"
theme = 'minimal-blog'

# Taxonomies
[taxonomies]
  tag = "tags"
  year = "years"

# Taxonomy permalinks
[permalinks]
  years = "/posts/:slug/"

# Site parameters
[params]
  author = "Dawid Macek"
  description = "Personal blog of Dawid Macek, a software engineer specializing in security. Deep dives into eBPF, Linux kernel, Rust, and low-level systems programming."
  email = "me@dawidmacek.com"
  github = "https://github.com/Palkovsky"
  linkedin = "https://www.linkedin.com/in/dawid-macek-8a1143205/"
  resume = "/resume.pdf"
#  photo = "/photo.png"
  og_image = "/og_image.svg"
  twitter = "@damacek"

[pagination]
  disableAliases = false
  pagerSize = 50
  path = 'page'

# Menu configuration
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 20

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "modus-operandi"  # https://gohugo.io/quick-reference/syntax-highlighting-styles
    tabWidth = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'